/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { ERC1155Contract } from "./ERC1155";
import { ERC1155RubicContract } from "./ERC1155Rubic";
import { ERC165Contract } from "./ERC165";
import { IAccessControlContract } from "./IAccessControl";
import { IERC1155Contract } from "./IERC1155";
import { IERC1155MetadataURIContract } from "./IERC1155MetadataURI";
import { IERC1155ReceiverContract } from "./IERC1155Receiver";
import { IERC165Contract } from "./IERC165";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "ERC1155"): ERC1155Contract;
      require(name: "ERC1155Rubic"): ERC1155RubicContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "IERC1155MetadataURI"): IERC1155MetadataURIContract;
      require(name: "IERC1155Receiver"): IERC1155ReceiverContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export { ERC1155Contract, ERC1155Instance } from "./ERC1155";
export { ERC1155RubicContract, ERC1155RubicInstance } from "./ERC1155Rubic";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export {
  IERC1155MetadataURIContract,
  IERC1155MetadataURIInstance,
} from "./IERC1155MetadataURI";
export {
  IERC1155ReceiverContract,
  IERC1155ReceiverInstance,
} from "./IERC1155Receiver";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
